Job Widget
yousty/yousty-widget pull request #6
Opened 2020-09-24 11:40 UTC by peelar

2020-09-24 13:21 UTC, adamszwaba requested changes
One change requested, but overall:
**Great damn job, man**.
I'm really impressed how fleshed out, full and well thought out the application is. I love the use of context, I'm loving the hooks, how you approached async functions and all of that... Really, nothing to touch on, I'm loving it.

2020-09-24 13:21 UTC, adamszwaba commented on src/Job/hooks.ts
> +  }, []);
Nice!

2020-09-24 13:21 UTC, adamszwaba commented on public/index.html
> +    Yousty.Job({
Request: Add this invokation and keep other commented out.
It becomes pretty apparent that we will need a proper sort of a workplace for these, some sort of a dashboard.

2020-09-24 13:21 UTC, adamszwaba commented on src/Job/api.ts
> +    street: string | null;
Are they really always returned from api?

2020-09-24 13:21 UTC, adamszwaba commented on src/Job/components/ContentBox/ContentBox.ts
> +export default styled(Box)<{ size: BoxSize }>`
To save a bit on the component, I suggest moving to `div` instead of `Box`
```suggestion
export default styled.div<{ size: BoxSize }>`
```

2020-09-24 13:21 UTC, adamszwaba commented on src/Job/components/Form/Form.tsx
> +  const { search } = React.useContext(ConfigContext);
I like the use of this context, and contexts overall. I should use it in the Gallery, it seems.

2020-10-02 07:27 UTC, merged

2020-10-05 09:57 UTC, swilgosz reviewed
Looks great! I love that we've started adding tests to react apps. Just wondering, are they hooked up to CI already?

2020-10-05 09:57 UTC, swilgosz commented on public/index.html
> +    // Yousty.Gallery({
Is it necessary to leave it here?